strict: true

site_name: '' # actual site name 'ThingPulse' is present in the logo and doesn't need to be repeated
site_url: https://docs.thingpulse.com/
site_description: ThingPulse docs
site_author: Marcel Stör & Dani Eichhorn
repo_name: thingpulse/docs
repo_url: https://github.com/thingpulse/docs
copyright: Copyright &copy; 2023 <a href="https://thingpulse.com">ThingPulse</a>.

# Configuration
theme:
  name: material
  logo: img/logo.svg
  favicon: img/favicon.ico

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: orange
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

  features:
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button
    - content.code.copy

extra:
  # https://squidfunk.github.io/mkdocs-material/getting-started/#adding-social-links
  social:
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/thingpulse
    - icon: fontawesome/brands/github
      link: https://github.com/thingpulse
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/thingpulse
  analytics:
    provider: google
    property: G-V8ZHG66YBG

nav:
  - Home: index.md
  - support.md
  - Guides:
    - ESP32 Color Kit Grande: guides/esp32-color-kit-grande.md
    - AMo - CO2 Monitor: guides/amo-co2-monitor.md
    - Icon64 - ESP32 with RBG LED & audio: guides/icon64-esp32-rgb-led-audio.md
    - ESP8266 IoT Starter Kit: guides/iot-starter-kit.md
    - WiFi Color Display Kit: guides/wifi-color-display-kit.md
    - 2.9″ ESPaper Plus Kit: guides/espaper-plus-kit.md
    - 2.9″ ESPaper Lite Kit: guides/espaper-lite-kit.md
    - 4.2″ ESPaper Plus Kit: guides/42-espaper-plus-kit.md
    - ESPaper Calendar: guides/espaper-calendar.md
  - How-tos:
    - Create OpenWeatherMap API key: how-tos/openweathermap-key.md
    - how-tos/install-drivers.md
    - how-tos/Arduino-IDE-for-ESP8266.md
  - Hardware specs:
    - WiFi Color Display Kit: specs/wifi-color-display-kit.md
    - 2.9" ESPaper Lite and Plus Kit: specs/2_9-espaper-kit-dimensions.md

markdown_extensions:
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition
  - toc:
      permalink: §
  # https://python-markdown.github.io/extensions/definition_lists/
  - def_list
  # https://github.com/mkdocs/mkdocs/issues/777#issuecomment-308266201
  - markdown_include.include:
      base_path: docs
  # https://facelessuser.github.io/pymdown-extensions/
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde

