strict: true

site_name: '' # actual site name 'ThingPulse' is present in the logo and doesn't need to be repeated
site_url: https://docs.thingpulse.com/
site_description: ThingPulse docs
site_author: Marcel Stör & Dani Eichhorn
repo_name: thingpulse/docs
repo_url: https://github.com/thingpulse/docs
copyright: Copyright &copy; 2018 <a href="https://thingpulse.com">ThingPulse</a>.

extra_css:
  - css/thingpulse.css

# Configuration
theme:
  name: material
  logo: ../img/logo.svg
  favicon: ../img/favicon.ico

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: white
    accent: orange

extra:
  # https://squidfunk.github.io/mkdocs-material/getting-started/#adding-social-links
  social:
    - type: facebook
      link: https://facebook.com/thingpulse
    - type: github-alt
      link: https://github.com/thingpulse
    - type: twitter
      link: https://twitter.com/thingpulse

nav:
  - Home: index.md
  - support.md
  - Guides:
    - 2.9″ ESPaper Plus Kit: guides/espaper-plus-kit.md
    - 2.9″ ESPaper Lite Kit: guides/espaper-lite-kit.md
    - 4.2″ ESPaper Plus Kit: guides/42-espaper-plus-kit.md
    - ESPaper Calendar: guides/espaper-calendar.md
    - ESP8266 IoT Starter Kit: guides/iot-starter-kit.md
    - WiFi Color Display Kit: guides/wifi-color-display-kit.md
  - How-tos:
    - Create OpenWeatherMap API key: how-tos/openweathermap-key.md
    - how-tos/install-drivers.md
    - how-tos/Arduino-IDE-for-ESP8266.md
  - Hardware specs:
    - WiFi Color Display Kit: specs/wifi-color-display-kit.md
    - 2.9" ESPaper Lite and Plus Kit: specs/2_9-espaper-kit-dimensions.md

google_analytics:
  - 'UA-112435176-4'
  - 'auto'

markdown_extensions:
  # https://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - admonition
  - toc:
      permalink: §
  # https://python-markdown.github.io/extensions/definition_lists/
  - def_list
  # https://github.com/mkdocs/mkdocs/issues/777#issuecomment-308266201
  - markdown_include.include:
      base_path: docs
  # https://facelessuser.github.io/pymdown-extensions/
  # https://squidfunk.github.io/mkdocs-material/extensions/pymdown/
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.inlinehilite
  - pymdownx.betterem:
      smart_enable: all
