strict: true

site_name: <img id="logo" src="https://thingpulse.com/assets/ThingPulse.svg" width="100">
site_url: https://docs.thingpulse.com/
site_description: ThingPulse docs
site_author: Marcel Stör & Dani Eichhorn
repo_url: https://github.com/thingpulse/docs
copyright: Copyright &copy; 2018 <a href="https://thingpulse.com">ThingPulse</a>.

# theme: cinder     # https://sourcefoundry.org/cinder/
# theme: material   # https://github.com/squidfunk/mkdocs-material
# theme: windmill   # https://github.com/gristlabs/mkdocs-windmill
# theme option mkdocs-bootswatch master branch

theme:
  name: mkdocs
  custom_dir: custom_theme

extra_css:
  - css/thingpulse.css

pages:
  - Home: index.md
  - Guides:
    - 2.9″ ESPaper Plus Kit: guides/espaper-plus-kit.md
    - guides/wifi-color-display-kit.md
  - How-tos:
    - how-tos/wunderground-key.md
    - how-tos/install-drivers.md

markdown_extensions:
  # http://pythonhosted.org/Markdown/extensions/admonition.html
  # supported types by base MkDocs theme: note, warning, danger
  - admonition:
  - toc:
      permalink: 
  # https://python-markdown.github.io/extensions/definition_lists/
  - def_list:
  # https://github.com/mkdocs/mkdocs/issues/777#issuecomment-308266201
  - markdown_include.include:
      base_path: docs

plugins:
  - search
